apiVersion: v1
kind: ReplicationController
metadata:
  name: fileapi-rc
  labels:
    app: fileapi
spec:
  replicas: 3
  selector:
    app: fileapi
  template:
    metadata:
      labels:
        app: fileapi
    spec:
        containers:
          - name: fileapi-pod
            image: centos7/fileapi:v1
            env:       
              - name: "ENGINE"
                value: "DEFAULT"
              - name: "MAX_WORKERS"
                value: "5"
            ports:
              - containerPort: 50051
                name: http
                protocol: TCP   
